### PR TITLE
Fix for SerializableCollection::children_if

### LINKED ISSUE #1400: SerializableCollection::children_if doesn't recurse correctly
## C++ Repro

the assertion at the end of this program fails:

```c++
#include <iostream>

#include "opentimelineio/clip.h"
#include "opentimelineio/errorStatus.h"
#include "opentimelineio/serializableObject.h"
#include "opentimelineio/track.h"
#include "opentimelineio/timeline.h"
#include "opentimelineio/serializableCollection.h"

namespace otio = opentimelineio::OPENTIMELINEIO_VERSION;

int
main(void)
{
    opentimelineio::v1_0::ErrorStatus err;

    // make a clip
    otio::SerializableObject::Retainer<otio::Clip> cl = new otio::Clip();

    // put it in a track
    otio::SerializableObject::Retainer<otio::Track> tr = new otio::Track();
    tr->append_child(cl);
    
    // check track
    auto result = tr->children_if<otio::Clip>(&err);
    assert (result.size() == 1);
    result.clear();

    // Make a timeline and add the track
    otio::SerializableObject::Retainer<otio::Timeline> tl = new otio::Timeline();
    tl->tracks()->append_child(tr);

    result = tl->children_if<otio::Clip>(&err);
    assert (result.size() == 1);
    result.clear();

    // Make a serializableCollection and then add the timeline
    otio::SerializableObject::Retainer<otio::SerializableCollection> sc = new otio::SerializableCollection();
    result = sc->children_if<otio::Clip>(&err, {}, false);

    // fail
    assert (result.size() == 1);
    result.clear();

    std::cout << "success" << std::endl;
}
```

## Python Repro
```python
import opentimelineio as otio

cl = otio.schema.Clip()

tr = otio.schema.Track()
tr.append(cl)

assert len(tr.clip_if()) == 1

tl = otio.schema.Timeline()
tl.tracks.append(tr)

assert len(tl.clip_if()) == 1

sc = otio.schema.SerializableCollection()
sc.append(tl)

# fails
assert len(sc.clip_if()) == 1
```

## Parameters are not wrapped

Note that despite the comment/argument here:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/8cdda64f5ef924855ce503822e1aeb125e6b011e/src/py-opentimelineio/opentimelineio/schema/track.py#L6

The `shallow_search` parameter is not passed through to the C++ function.

## Related
-  `shallow_search` parameter does not appear to be exposed to python
- there appear to be no python tests that call `clip_if` and the only test that calls `children_if` is the cmx_edl tests

## Items
- [ ] bug in `SerializableCollection::children_if` (should find the clip in the test above)
- [ ] exposing parameters of `clip_if` / `children_if`
- [ ] add python unit tests for `clip_if` and `children_if`

### PR DESCRIPTION
**Pull request by darbyjohnston**
Signed-off-by: Darby Johnston <darbyjohnston@yahoo.com>

Fixes #1400

Fixes an issue where SerializableCollection::children_if doesn't recurse into timelines. I'm marking this as a draft for now since it doesn't address all of the items in the issue (Python tests and missing arguments).

### CODE REVIEW

File: src/opentimelineio/serializableCollection.h [hunk 1]
```diff
@@ -129,6 +130,19 @@ SerializableCollection::children_if(
                     out.push_back(valid_child);
                 }
             }
+            else if (auto timeline = dynamic_cast<Timeline*>(child.value))
+            {
+                const auto valid_children =
+                    timeline->children_if<T>(error_status, search_range);
```
Comment (ssteinbach) [inline src/opentimelineio/serializableCollection.h:136]: Thanks for putting this together, @darbyjohnston!  This is pretty straightforward.  @meshula I think we'll need to return to this argument because it isn't specified what space the `search_range` is in.  In the case of a serializable collection, which doesn't have a temporal relationship between its children, I could see dropping this argument entirely.  For timelines, if its in the global space, then the offset should be subtracted first to get into the space of the `.tracks` stack.

I also sort of wonder if Serializable collection needs children_if/clip_if?  or needs one that does this kind of recursion?  I wonder if it makes more sense to drop it or make it always shallow search so that you can then operate on the results of this in a consistent way.  Any thoughts or opinions?  @jminor @reinecke 

We could leave it as is - or as it is after this PR or I could see an argument for dropping it.

File: src/opentimelineio/serializableCollection.h [hunk 2]
```diff
@@ -5,6 +5,7 @@
 
 #include "opentimelineio/composition.h"
 #include "opentimelineio/serializableObjectWithMetadata.h"
+#include "opentimelineio/timeline.h"
```
Comment (ssteinbach) [inline src/opentimelineio/serializableCollection.h:8]: This might be a good time to break out test_serializableCollection.cpp

File: src/opentimelineio/serializableCollection.h (hunk 1 above)
Comment (meshula) [reply src/opentimelineio/serializableCollection.h:136]: 1) I assume that in the case of a timeline, the range would be in the timeline's space, so wouldn't need a subtraction?

2) I do wonder how deep down the rabbit hole we should go in addressing the initial report. I'm inclined  to suggest solving for Timeline is sufficient for 0.15.0, but more fundamental thinking about *_if seems prime territory for exploration in 0.16.0.

File: src/opentimelineio/serializableCollection.h [hunk 3]
```diff
@@ -129,6 +130,19 @@ SerializableCollection::children_if(
                     out.push_back(valid_child);
                 }
             }
+            else if (auto timeline = dynamic_cast<Timeline*>(child.value))
```
Comment (rogernelson) [inline src/opentimelineio/serializableCollection.h:133]: I'm not sure how far down the c++ template rabbit hole its worth going for this, but you could use SFINAE to check if `child.value` has the method `children_if<T>`, rather than casting to every type known to have it.  That would ensure the list would always remain exhaustive.

Comment (darbyjohnston) [reply src/opentimelineio/serializableCollection.h:133]: Interesting, I didn't know about the SFINAE, I'll check it out.

File: src/opentimelineio/serializableCollection.h (hunk 2 above)
Comment (darbyjohnston) [reply src/opentimelineio/serializableCollection.h:8]: Good idea, I also broke out test_track.cpp and test_timeline.cpp since they also have ```children_if()```.

Comment (ssteinbach) [reply src/opentimelineio/serializableCollection.h:8]: awesome, thanks!

File: src/opentimelineio/serializableCollection.h (hunk 3 above)
Comment (rogernelson) [reply src/opentimelineio/serializableCollection.h:133]: It stands for Substitution Failure Is Not An Error, which is essentially a technique in template programming to filter in the things you are interested in, and just ignore everything else that doesn't match.

Here is a relevant example from stack overflow:
https://stackoverflow.com/questions/87372/check-if-a-class-has-a-member-function-of-a-given-signature

Comment (rogernelson) [reply src/opentimelineio/serializableCollection.h:133]: I think adding something like this (maybe best suited for a utility file header):
```
template<typename, typename T>
struct has_children_if {
    static_assert(
        std::integral_constant<T, false>::value,
        "Second template parameter needs to be of function type.");
};

template<typename C, typename Ret, typename... Args>
struct has_children_if<C, Ret(Args...)> {
private:
    template<typename T>
    static constexpr auto check(T*) -> typename
        std::is_same<
            decltype( std::declval<T>().children_if( std::declval<Args>()... ) ),
            Ret 
        >::type;

    template<typename>
    static constexpr std::false_type check(...);

    typedef decltype(check<C>(0)) type;

public:
    static constexpr bool value = type::value;
};

bool has_children_if_method(SerializableObject const & so) {
   return has_children_if<so, std::vector<Retainer<T>>(ErrorStatus*, optional<TimeRange>, bool)>::value
}
```

And then replacing if/else chain with this single if
```
if( has_children_if_method(*(child.value)) ) {
```
_might_ do the trick (warning: I did not test any of that, there are probably errors).

Of course, putting a virtual has_children_if method in the SerializableObject class that returns false and overloading it the appropriate base classes to return true would also do the trick.  That is much easier to understand code, but at the same time I find once you go down that path, over time more and more of those start getting introduced and whenever you add a new class you have a bunch has_* methods that you may not know about and can effect the behaviour or your class is subtle, hard-to-debug ways.

Comment (darbyjohnston) [reply src/opentimelineio/serializableCollection.h:133]: I need to learn more about modern C++ templates before trying out that code, that's quite formidable looking. :) @ssteinbach brought up the question of whether SerializableCollection should support recursive searching, maybe we should come to a consensus on that before getting to far with the implementation.

**Comment by darbyjohnston** [comment]
I think I have addressed all the items from the issue as well as adding more consistent use of the "shallow_search" parameter to the various functions. @rogernelson has some interesting thoughts on a more efficient implementation of the "children_if" function, but maybe we need to decide whether the recursive searching functionality is actually appropriate for SerializableCollection.

**Comment by ssteinbach** [comment]
I think we should probably not do a major functionality switch on `SerializableCollection` right now, since we're in a release process.  That is a conversation we can have for beta 16.  Lets review this PR with its current functionality, and circle back to that other discussion later.

Thanks @darbyjohnston!  I'll take a look at the code.

File: src/opentimelineio/serializableCollection.h (hunk 3 above)
Comment (ssteinbach) [reply src/opentimelineio/serializableCollection.h:133]: As I noted in the other comment, I think sticking with this for now is ok.  We can have a bigger discussion about adopting something more duck-type-y like the SFINAE that Roger proposes or even removing this function in the next beta.

Thanks for raising that @rogernelson!

File: src/py-opentimelineio/opentimelineio/schema/serializable_collection.py [hunk 4]
```diff
@@ -31,7 +31,8 @@ def __repr__(self):
 
 
 @add_method(_otio.SerializableCollection)
-def each_child(self, search_range=None, descended_from_type=_otio.Composable):
+def each_child(self, search_range=None, descended_from_type=_otio.Composable,
```
Comment (ssteinbach) [inline src/py-opentimelineio/opentimelineio/schema/serializable_collection.py:34]: We marked these as deprecated in 0.14.  We should add an issue to remove these in 0.16.

File: tests/test_timeline.cpp [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+        otio::SerializableObject::Retainer<otio::Track> tr =
+            new otio::Track();
+        tr->append_child(cl);
+        otio::SerializableObject::Retainer<otio::Timeline> tl =
+            new otio::Timeline();
+        tl->tracks()->append_child(tr);
+        opentimelineio::v1_0::ErrorStatus err;
+        auto result = tl->children_if<otio::Clip>(&err);
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl);
```
Comment (ssteinbach) [inline tests/test_timeline.cpp:34]:
```suggestion
        assertEqual(result[0], cl)
```

Should this be `==` instead of `=`?  Or `assertEqual`?

File: tests/test_timeline.cpp [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+        tr->append_child(cl0);
+        tr->append_child(cl1);
+        tr->append_child(cl2);
+        otio::SerializableObject::Retainer<otio::Timeline> tl =
+            new otio::Timeline();
+        tl->tracks()->append_child(tr);
+        opentimelineio::v1_0::ErrorStatus err;
+        auto result = tl->children_if<otio::Clip>(&err, range);
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl0);
```
Comment (ssteinbach) [inline tests/test_timeline.cpp:60]:
```suggestion
        assertEqual(result[0], cl0);
```

Same question here about `assertTrue` vs `assertEqual`

File: tests/test_timeline.cpp [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+        tr->append_child(cl);
+        otio::SerializableObject::Retainer<otio::Timeline> tl =
+            new otio::Timeline();
+        tl->tracks()->append_child(tr);
+        opentimelineio::v1_0::ErrorStatus err;
+        auto result = tl->children_if<otio::Clip>(&err, nullopt, true);
+        assertEqual(result.size(), 0);
+        result = tl->children_if<otio::Clip>(&err, nullopt, false);
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl);
```
Comment (ssteinbach) [inline tests/test_timeline.cpp:78]: Same question here:

```suggestion
        assertEqual(result[0], cl);
```

File: tests/test_timeline.py [hunk 8]
```diff
@@ -557,6 +557,48 @@ def test_tracks_set_null_tracks(self):
...
 
+    def test_children_if(self):
+        cl = otio.schema.Clip()
+        tr = otio.schema.Track()
+        tr.append(cl)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        result = tl.children_if(otio.schema.Clip)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl)
```
Comment (ssteinbach) [inline tests/test_timeline.py:568]:
```suggestion
        self.assertEqual(result[0], cl)
```

File: tests/test_timeline.py [hunk 9]
```diff
@@ -557,6 +557,48 @@ def test_tracks_set_null_tracks(self):
...
+        cl2.source_range = range
+        tr = otio.schema.Track()
+        tr.append(cl0)
+        tr.append(cl1)
+        tr.append(cl2)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        result = tl.children_if(otio.schema.Clip, range)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl0)
```
Comment (ssteinbach) [inline tests/test_timeline.py:588]:
```suggestion
        self.assertEqual(result[0], cl0)
```

File: tests/test_timeline.py [hunk 10]
```diff
@@ -557,6 +557,48 @@ def test_tracks_set_null_tracks(self):
...
+        cl = otio.schema.Clip()
+        tr = otio.schema.Track()
+        tr.append(cl)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        result = tl.children_if(otio.schema.Clip, shallow_search=True)
+        self.assertEqual(len(result), 0)
+        result = tl.children_if(otio.schema.Clip, shallow_search=False)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl)
```
Comment (ssteinbach) [inline tests/test_timeline.py:600]:
```suggestion
        self.assertEqual(result[0], cl)
```

File: tests/test_track.cpp [hunk 11]
```diff
@@ -0,0 +1,113 @@
...
+        using namespace otio;
+        otio::SerializableObject::Retainer<otio::Clip> cl =
+            new otio::Clip();
+        otio::SerializableObject::Retainer<otio::Track> tr =
+            new otio::Track();
+        tr->append_child(cl);
+        opentimelineio::v1_0::ErrorStatus err;
+        auto result = tr->children_if<otio::Clip>(&err);
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl);
```
Comment (ssteinbach) [inline tests/test_track.cpp:31]:
```suggestion
        assertEqual(result[0], cl);
```

File: tests/test_track.cpp [hunk 12]
```diff
@@ -0,0 +1,113 @@
...
+            new otio::Track();
+        tr->append_child(cl0);
+        tr->append_child(cl1);
+        tr->append_child(cl2);
+        opentimelineio::v1_0::ErrorStatus err;
+        auto result = tr->children_if<otio::Clip>(
+            &err,
+            TimeRange(RationalTime(0.0, 24.0), RationalTime(24.0, 24.0)));
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl0);
```
Comment (ssteinbach) [inline tests/test_track.cpp:56]:
```suggestion
        assertEqual(result[0], cl0);
```

File: tests/test_track.cpp [hunk 13]
```diff
@@ -0,0 +1,113 @@
...
+        result = tr->children_if<otio::Clip>(
+            &err,
+            TimeRange(RationalTime(24.0, 24.0), RationalTime(24.0, 24.0)));
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl1);
```
Comment (ssteinbach) [inline tests/test_track.cpp:61]:
```suggestion
        assertEqual(result[0], cl1);
```

File: tests/test_track.cpp [hunk 14]
```diff
@@ -0,0 +1,113 @@
...
+        result = tr->children_if<otio::Clip>(
+            &err,
+            TimeRange(RationalTime(48.0, 24.0), RationalTime(24.0, 24.0)));
+        assertEqual(result.size(), 1);
+        assertTrue(result[0] = cl1);
```
Comment (ssteinbach) [inline tests/test_track.cpp:66]:
```suggestion
        assertEqual(result[0], cl1);
```

File: tests/test_track.py [hunk 15]
```diff
@@ -0,0 +1,58 @@
...
+        tr = otio.schema.Track()
+        tr.append(cl0)
+        tr.append(st)
+        result = tr.children_if(otio.schema.Clip, shallow_search=True)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl0)
+        result = tr.children_if(otio.schema.Clip, shallow_search=False)
+        self.assertEqual(len(result), 2)
+        self.assertTrue(result[0], cl0)
+        self.assertTrue(result[1], cl1)
```
Comment (ssteinbach) [inline tests/test_track.py:54]:
```suggestion
        self.assertEqual(result[0], cl0)
        self.assertEqual(result[1], cl1)
```

**Review by ssteinbach — COMMENTED** [review]
Looks good. Saw (maybe) a copy paste typo in the unit tests?  I probably missed some but I might just be misunderstanding the use of `assertTrue`, too.  Let me know what you think!

File: src/py-opentimelineio/opentimelineio/schema/serializable_collection.py (hunk 4 above)
Comment (darbyjohnston) [reply src/py-opentimelineio/opentimelineio/schema/serializable_collection.py:34]: Thanks, good catch on the asserts! It's a bit embarrassing creating a bug and then copying and pasting it half a dozen times. :)

Comment (darbyjohnston) [reply src/py-opentimelineio/opentimelineio/schema/serializable_collection.py:34]: New issue to remove the deprecated functions: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/issues/1409

File: tests/test_serializable_collection.py [hunk 16]
```diff
@@ -71,6 +71,54 @@ def test_repr(self):
...
+        tr.append(cl0)
+        tr.append(cl1)
+        tr.append(cl2)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        sc = otio.schema.SerializableCollection()
+        sc.append(tl)
+        result = sc.children_if(otio.schema.Clip, range)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl0)
```
Comment (ssteinbach) [inline tests/test_serializable_collection.py:106]: Is this also meant to be `assertEqual`?
```suggestion
        self.assertEqual(result[0], cl0)
```

File: tests/test_serializable_collection.py [hunk 17]
```diff
@@ -71,6 +71,54 @@ def test_repr(self):
...
+        tr.append(cl)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        sc = otio.schema.SerializableCollection()
+        sc.append(tl)
+        result = sc.children_if(otio.schema.Clip, shallow_search=True)
+        self.assertEqual(len(result), 0)
+        result = sc.children_if(otio.schema.Clip, shallow_search=False)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl)
```
Comment (ssteinbach) [inline tests/test_serializable_collection.py:120]:
```suggestion
        self.assertEqual(result[0], cl)
```

File: tests/test_serializable_collection.py [hunk 18]
```diff
@@ -71,6 +71,54 @@ def test_repr(self):
...
+        cl = otio.schema.Clip()
+        tr = otio.schema.Track()
+        tr.append(cl)
+        tl = otio.schema.Timeline()
+        tl.tracks.append(tr)
+        sc = otio.schema.SerializableCollection()
+        sc.append(tl)
+        result = sc.children_if(otio.schema.Clip)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl)
```
Comment (ssteinbach) [inline tests/test_serializable_collection.py:84]:
```suggestion
        self.assertEqual(result[0], cl)
```

File: tests/test_track.py [hunk 19]
```diff
@@ -0,0 +1,58 @@
...
+
+class TrackTests(unittest.TestCase, otio_test_utils.OTIOAssertions):
+
+    def test_children_if(self):
+        cl = otio.schema.Clip()
+        tr = otio.schema.Track()
+        tr.append(cl)
+        result = tr.children_if(otio.schema.Clip)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl)
```
Comment (ssteinbach) [inline tests/test_track.py:20]:
```suggestion
        self.assertEqual(result[0], cl)
```

File: tests/test_track.py [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+        cl1.source_range = range
+        cl2 = otio.schema.Clip()
+        cl2.source_range = range
+        tr = otio.schema.Track()
+        tr.append(cl0)
+        tr.append(cl1)
+        tr.append(cl2)
+        result = tr.children_if(otio.schema.Clip, range)
+        self.assertEqual(len(result), 1)
+        self.assertTrue(result[0], cl0)
```
Comment (ssteinbach) [inline tests/test_track.py:38]:
```suggestion
        self.assertEqual(result[0], cl0)
```

**Review by ssteinbach — CHANGES_REQUESTED** [review]
A few more `assertTrue` still in there

File: tests/test_serializable_collection.py (hunk 16 above)
Comment (darbyjohnston) [reply tests/test_serializable_collection.py]: Oops, sorry, I forgot the Python tests. Should be fixed now.

**Review by ssteinbach — APPROVED** [review]
Alright, this looks great.  Thanks @darbyjohnston
